### ISSUE TITLE
Deprecation cop does not show what selectors are deprecated in my local style.less file

### ISSUE THREAD

**Issue by deepj** [atom/deprecation-cop#47]
I guess this is a bug not showing the deprecated selectors. Because in case of `atom-lint` the deprecated selectors are shown (see the screenshot above)

![screen shot 2015-05-19 at 05 53 36](https://cloud.githubusercontent.com/assets/33736/7695169/95f85e48-fdeb-11e4-8d20-0360bdf2610b.png)

Versions: Atom.0.199.0, deprecation-cop 0.48.0

My `style.less` file:

```less
/*
 * Your Stylesheet
 *
 * This stylesheet is loaded when Atom starts up and is reloaded automatically
 * when it is changed.
 *
 * If you are unfamiliar with LESS, you can read more about it here:
 * http://www.lesscss.org
 */

.editor .markup.underline.link.hyperlink {
  text-decoration: underline;
}
```
